# Tensors

In [1]:
import torch
import numpy as np

## Initializing a tensor

In [5]:
# from data

data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

print(data)
print(x_data)

[[1, 2], [3, 4]]
tensor([[1, 2],
        [3, 4]])


In [3]:
print(type(data))
print(type(x_data))

<class 'list'>
<class 'torch.Tensor'>


In [7]:
# from numpy array

np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(np_array)
print(x_np)

[[1 2]
 [3 4]]
tensor([[1, 2],
        [3, 4]], dtype=torch.int32)


In [8]:
# from another tensor

x_ones = torch.ones_like(x_data)
print(x_ones)

x_rand = torch.rand_like(x_data, dtype=torch.float)
print(x_rand)

tensor([[1, 1],
        [1, 1]])
tensor([[0.6008, 0.3021],
        [0.1679, 0.7355]])


In [9]:
# with random or constant values

shape = (2, 3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(rand_tensor)
print(ones_tensor)
print(zeros_tensor)

tensor([[0.4832, 0.9506, 0.7013],
        [0.0534, 0.5738, 0.0723]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


## Attributest of a tensor

In [10]:
tensor = torch.rand(3, 4)
print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


## Operations on Tensors

In [12]:
# Use GPU
if torch.cuda.is_available():
    tensor = tensor.to("cuda")

In [14]:
# standard numpy-like indexing and slicing

tensor = torch.ones(4, 4)
print(tensor)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")
tensor[:, 1] = 0
print(tensor)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [15]:
# joining tensor

t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [16]:
# Arithmetic operations
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)

z1 = tensor * tensor
z2 = tensor.mul(tensor)
z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

print(y3)
print(z3)

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [18]:
# Single-element tensors
agg = tensor.sum()
agg_item = agg.item()
print(agg, type(agg))
print(agg_item, type(agg_item))

tensor(12.) <class 'torch.Tensor'>
12.0 <class 'float'>


In [21]:
# In-place operation

print(f"{tensor} \n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


## Bridge with NumPy

In [26]:
# Tensor to NumPy array

t = torch.ones(5)
print(t)
print(type(t))
n = t.numpy()
print(n)
print(type(n))

tensor([1., 1., 1., 1., 1.])
<class 'torch.Tensor'>
[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


In [27]:
t.add_(1)
print(t)
print(type(t))
print(n)
print(type(n))

tensor([2., 2., 2., 2., 2.])
<class 'torch.Tensor'>
[2. 2. 2. 2. 2.]
<class 'numpy.ndarray'>


In [29]:
# NumPy array to Tensor

n = np.ones(5)
t = torch.from_numpy(n)
print(t)
print(type(t))
print(n)
print(type(n))

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
<class 'torch.Tensor'>
[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


In [30]:
np.add(n, 1, out=n)
print(t)
print(type(t))
print(n)
print(type(n))

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
<class 'torch.Tensor'>
[2. 2. 2. 2. 2.]
<class 'numpy.ndarray'>
