# Build the Neural Network

In [2]:
import os
import torch
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets, transforms

In [3]:
# Get Device for Training

device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using {device}")

Using cuda


In [4]:
# Define the Class

class NeuralNetwork(nn.Module):
    def __init__(self):
        super(NeuralNetwork, self).__init__()
        self.flatten = nn.Flatten()
        self.linear_relu_stack = nn.Sequential(
            nn.Linear(28 * 28, 512),
            nn.ReLU(),
            nn.Linear(512, 512),
            nn.ReLU(),
            nn.Linear(512, 10),
        )
    
    def forward(self, x):
        x = self.flatten(x)
        logits = self.linear_relu_stack(x)
        return logits

In [5]:
model = NeuralNetwork().to(device)
print(model)

NeuralNetwork(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): ReLU()
    (4): Linear(in_features=512, out_features=10, bias=True)
  )
)


In [8]:
X = torch.rand(1, 28, 28, device=device)
logits = model(X)
pred_probab = nn.Softmax(dim=1)(logits)
print(pred_probab.shape)
y_pred = pred_probab.argmax(1)
print(y_pred.shape)
print(f"{y_pred}")

torch.Size([1, 10])
torch.Size([1])
tensor([9], device='cuda:0')


In [10]:
# Model Layers

input_image = torch.rand(3, 28, 28)
print(input_image.size())

torch.Size([3, 28, 28])


In [11]:
# nn.Flatten

flatten = nn.Flatten()
flat_image = flatten(input_image)
print(flat_image.size())

torch.Size([3, 784])


In [12]:
# nn.Linear

layer1 = nn.Linear(in_features=28*28, out_features=20)
hidden1 = layer1(flat_image)
print(hidden1.size())

torch.Size([3, 20])


In [14]:
# nn.ReLU
print(hidden1)
hidden1_o = nn.ReLU()(hidden1)
print(hidden1_o.size())
print(hidden1_o)

tensor([[-0.2484, -0.3379, -0.2967,  0.4775, -0.6106,  0.2296, -0.0512, -0.2448,
          0.0186, -0.0043, -0.4389, -0.3300,  0.1727,  0.0423, -0.2811,  0.0621,
         -0.3077, -0.3754, -0.4284,  0.7207],
        [-0.3765, -0.1081, -0.6272,  0.3517, -0.5635, -0.1534,  0.0411, -0.3953,
         -0.2131,  0.1834, -0.5695, -0.4337,  0.2716,  0.0094, -0.4082,  0.2470,
         -0.2018, -0.2012,  0.1686,  0.2375],
        [ 0.0411, -0.0712, -0.1881,  0.4351, -0.4433, -0.0718,  0.0191, -0.3180,
         -0.2050,  0.0974, -0.4958, -0.0790, -0.1932,  0.0946,  0.2808, -0.1864,
         -0.0281, -0.5721, -0.1055,  0.4397]], grad_fn=<AddmmBackward0>)
torch.Size([3, 20])
tensor([[0.0000, 0.0000, 0.0000, 0.4775, 0.0000, 0.2296, 0.0000, 0.0000, 0.0186,
         0.0000, 0.0000, 0.0000, 0.1727, 0.0423, 0.0000, 0.0621, 0.0000, 0.0000,
         0.0000, 0.7207],
        [0.0000, 0.0000, 0.0000, 0.3517, 0.0000, 0.0000, 0.0411, 0.0000, 0.0000,
         0.1834, 0.0000, 0.0000, 0.2716, 0.0094, 0.0000, 0.2

In [16]:
# nn.Sequential

seq_modules = nn.Sequential(
    flatten,
    layer1,
    nn.ReLU(),
    nn.Linear(20, 10)
)

input_image = torch.rand(3, 28, 28)
logits = seq_modules(input_image)
print(logits)

tensor([[ 0.1532, -0.1485, -0.0472,  0.2911, -0.0217,  0.1760, -0.0762, -0.0428,
          0.3083,  0.2327],
        [ 0.2626, -0.0887, -0.0595,  0.2992, -0.1280,  0.1350, -0.0786,  0.0767,
          0.3040,  0.2581],
        [ 0.2300, -0.1958,  0.0825,  0.3176, -0.0747,  0.2438, -0.1010,  0.0588,
          0.3208,  0.3377]], grad_fn=<AddmmBackward0>)


In [17]:
model.named_parameters

<bound method Module.named_parameters of NeuralNetwork(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): ReLU()
    (4): Linear(in_features=512, out_features=10, bias=True)
  )
)>

In [31]:
# Model Parameters
print(model)

for name, param in model.named_parameters():
    print(f"{name}, {param.size()}")

NeuralNetwork(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): ReLU()
    (4): Linear(in_features=512, out_features=10, bias=True)
  )
)
linear_relu_stack.0.weight, torch.Size([512, 784])
linear_relu_stack.0.bias, torch.Size([512])
linear_relu_stack.2.weight, torch.Size([512, 512])
linear_relu_stack.2.bias, torch.Size([512])
linear_relu_stack.4.weight, torch.Size([10, 512])
linear_relu_stack.4.bias, torch.Size([10])
