# Automatic differentiation wiht torch.autograd

In [1]:
import torch

x = torch.ones(5)
y = torch.zeros(3)
w = torch.randn(5, 3, requires_grad=True)
b = torch.randn(3, requires_grad=True)
z = torch.matmul(x, w) + b
loss = torch.nn.functional.binary_cross_entropy_with_logits(z, y)

In [3]:
# Tensro, Functions and Computational Graph

print(f"{z.grad_fn}")
print(f"{loss.grad_fn}")

In [4]:
#  Computing Garadients

loss.backward()
print(w)
print(b)
print(w.grad)
print(b.grad)

tensor([[-0.3599,  1.4094, -0.6034],
        [-1.0057,  2.3251, -0.6218],
        [ 1.5153,  0.4902, -0.5081],
        [-0.0728,  0.1620,  1.5166],
        [ 0.7033,  0.1950, -0.3373]], requires_grad=True)
tensor([-0.5195,  0.9922,  2.3250], requires_grad=True)
tensor([[0.1883, 0.3321, 0.2849],
        [0.1883, 0.3321, 0.2849],
        [0.1883, 0.3321, 0.2849],
        [0.1883, 0.3321, 0.2849],
        [0.1883, 0.3321, 0.2849]])
tensor([0.1883, 0.3321, 0.2849])


In [5]:
# Disabling Gradient Tracking

z = torch.matmul(x, w) + b
print(z.requires_grad)

with torch.no_grad():
    z = torch.matmul(x, w) + b
print(z.requires_grad)

True
False


In [6]:
z = torch.matmul(x, w) + b
z_det = z.detach()
print(z_det.requires_grad)

False
