In [1]:
import torch
from torchvision.models import resnet18, ResNet18_Weights
model = resnet18(weights=ResNet18_Weights.DEFAULT)
data = torch.rand(1, 3, 64, 64)
labels = torch.rand(1, 1000)

In [2]:
pred = model(data)

In [3]:
loss = (pred - labels).sum()
print(loss)
loss.backward()

tensor(-506.8284, grad_fn=<SumBackward0>)


In [4]:
optim = torch.optim.SGD(model.parameters(), lr=1e-2, momentum=0.9)

In [5]:
optim.step()

In [6]:
# Differentiation in Autograd

import torch
a = torch.tensor([2., 3.], requires_grad=True)
b = torch.tensor([6., 4.], requires_grad=True)

In [7]:
Q = 3*a**3 - b**2

In [8]:
external_grad = torch.tensor([1., 1.])
Q.backward(gradient=external_grad)

In [9]:
print(9*a**2)
print(a.grad)

tensor([36., 81.], grad_fn=<MulBackward0>)
tensor([36., 81.])


In [10]:
print(-2*b)
print(b.grad)

tensor([-12.,  -8.], grad_fn=<MulBackward0>)
tensor([-12.,  -8.])


In [11]:
# frozen parameters

from torch import nn, optim
model = resnet18(weights=ResNet18_Weights.DEFAULT)

for param in model.parameters():
    param.requires_grad = False

model.fc = nn.Linear(512, 10)

optimizer = optim.SGD(model.parameters(), lr=1e-3, momentum=0.9)